name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Start backend
        run: npm run start &
        working-directory: ./backend

      - name: Wait for backend to be available
        run: npx wait-on tcp:27017

      - name: Verify backend is running
        run: curl -f http://localhost:3000/health || exit 1

      - name: Start frontend
        run: npm run dev &
        working-directory: ./frontend
        env:
          CI: true

      - name: Wait for frontend to be available
        run: npx wait-on http://localhost:3000

      - name: Verify frontend is running
        run: curl -f http://localhost:3000 || exit 1

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: ./frontend
