name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MONGO_URI: mongodb://localhost:27017/poatekdex # Ajuste conforme necessário

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Start backend
        run: npm run start &
        working-directory: ./backend
        env:
          MONGO_URI: ${{ env.MONGO_URI }}

      - name: Wait for backend to be available
        run: sleep 30 # Ajuste o tempo conforme necessário para garantir que o backend esteja disponível

      - name: Start frontend
        run: npm run dev
        working-directory: ./frontend
        env:
          CI: true

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: ./frontend